version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: airtable
    versions:
    - 0.11.0
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: husky
    versions:
    - 5.1.2
